name: Build GeoIP
on:
  workflow_dispatch:
  push:
    branches: [ master, main ]
    paths: [ 'geoip/**' ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4
        with:
          path: my_data

      - name: Checkout v2fly geoip builder
        uses: actions/checkout@v4
        with:
          repository: v2fly/geoip
          path: builder

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20'

      - name: Build geoip.dat
        run: |
          # Создаем конфиг для сборщика
          cat <<EOF > geoip_config.json
          {
            "input": [ { "type": "v2raygeoip", "action": "add", "args": { "uri": "my_data/geoip/" } } ],
            "output": [ { "type": "v2raygeoip", "action": "output", "args": { "uri": "release/geoip.dat" } } ]
          }
          EOF
          mkdir -p release
          cd builder
          go run ./ -c ../geoip_config.json

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: release/geoip.dat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
