name: Build Rules
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.20'

      - name: Install Compilers
        run: |
          go install github.com/v2fly/domain-list-community@latest
          go install github.com/v2fly/geoip@latest

      - name: Prepare directories
        run: |
          mkdir -p geosite
          mkdir -p geoip

      - name: Build geosite.dat
        run: |
          $(go env GOPATH)/bin/domain-list-community -datapath=geosite/ -outputname=geosite.dat

      - name: Build geoip.dat
        run: |
          # Создаем файл конфигурации для компилятора geoip
          cat <<EOF > geoip_config.json
          {
            "input": [
              {
                "type": "v2raygeoip",
                "action": "add",
                "args": {
                  "uri": "geoip/"
                }
              }
            ],
            "output": [
              {
                "type": "v2raygeoip",
                "action": "output",
                "args": {
                  "uri": "geoip.dat"
                }
              }
            ]
          }
          EOF
          # Запускаем компиляцию через конфиг
          $(go env GOPATH)/bin/geoip -c geoip_config.json

      - name: Release DAT files
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: |
            geosite.dat
            geoip.dat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
